### ISSUE TITLE
Windows Installer is flagged as malicious in Virustotal

### ISSUE THREAD

**Issue by mikedolx** [blizzard4591/openMittsu#81]
Hi,

I wanted to install the latest Version for Windows 10. Before installing I uploaded the installer to virustotal.com. After Uploading and scanning Virustotal showed me 1 positive result :  Trojan.Slntscn24.bVVB1s. 

Is there any library that might trigger a false positive?

I have tried the following installer:

- openmittsu_0.9.16plus18-ge870887-Windows-x86-Release.exe
- openmittsu_0.9.16plus18-ge870887-Windows-x64-Release.exe

Both trigger the Yandex engine and result in a positive for Trojan.Slntscn24.bVVB1s.

**Comment by blizzard4591** [comment]
I tried it just now with the ZIP version (https://www.virustotal.com/gui/file/d6aaa4412947b1f11b221eb2bef5d8f145e1864154dc618420c0c3fcbc3b1cbd/detection) and I see no positive hits, so if you do not need the installer, this could be an option.

Since the complete source is available, you can always build everything yourself.
The build machine looks clean, but of course I am no expert and can not guarantee this.
But one hit, and that one by Yandex... I don't really worry.
